---

- name: Uninstall Jenkins
  hosts: cicd
  gather_facts: true
  become: yes
  become_method: sudo
  tags: [remove]

  tasks:
  - name: Stop Jenkins server
    service:
      name: jenkins
      state: stopped

  - name: Uninstall packages
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - jenkins
